In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding='latin-1')
print(df.head())

   Area Code     Area  Item Code         Item  Element Code  \
0          4  Algeria       2501   Population           511
1          4  Algeria       2501   Population          5301
2          4  Algeria       2901  Grand Total           664
3          4  Algeria       2901  Grand Total           674
4          4  Algeria       2901  Grand Total           684

                                  Element             Unit     Y2014  \
0           Total Population - Both sexes     1000 persons  38924.00
1                Domestic supply quantity      1000 tonnes      0.00
2           Food supply (kcal/capita/day)  kcal/capita/day   3377.00
3  Protein supply quantity (g/capita/day)     g/capita/day     94.90
4      Fat supply quantity (g/capita/day)     g/capita/day     80.06

      Y2015     Y2016     Y2017     Y2018
0  39728.00  40551.00  41389.00  42228.00
1      0.00      0.00      0.00      0.00
2   3379.00   3372.00   3341.00   3322.00
3     94.35     94.72     92.82     91.83
4     79.36     77.40     80.19     77.28

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [4]:
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [6]:
# Question 3
element_group = df.groupby('Element').Y2017.sum()
print(element_group)

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [7]:
# Question 6
area_groupby = df.groupby('Area').Y2017.sum()
print(area_groupby)

Area
Algeria                         325644.27
Angola                          229159.57
Benin                           124771.22
Botswana                         22101.30
Burkina Faso                    101855.07
Cabo Verde                       14650.74
Cameroon                        232030.43
Central African Republic         29937.00
Chad                             71594.68
Comoros                             59.84
Congo                            41181.68
Côte d'Ivoire                   224599.01
Djibouti                         22729.91
Egypt                           866379.92
Eswatini                         54343.33
Ethiopia                        448683.76
Ethiopia PDR                         0.00
Gabon                            27979.64
Gambia                           23154.18
Ghana                           337599.06
Guinea                           98138.87
Guinea-Bissau                    19102.77
Kenya                           264660.66
Lesotho                          21267.96
Liberia                          29342.20
Madagascar                      131197.73
Malawi                          181098.71
Mali                            149928.33
Mauritania                      156665.46
Mauritius                        51114.83
Morocco                         388495.36
Mozambique                      161407.98
Namibia                          29874.89
Niger                           126707.58
Nigeria                        1483268.23
Rwanda                           73663.69
Sao Tome and Principe            12662.63
Senegal                          95681.15
Seychelles                         442.34
Sierra Leone                     55311.33
South Africa                    517590.54
Sudan                           239931.92
Sudan (former)                       0.00
Togo                             49841.88
Tunisia                         124167.20
Uganda                          213950.38
United Republic of Tanzania     322616.85
Zambia                          103223.77
Zimbabwe                         75919.34
Name: Y2017, dtype: float64

In [9]:
missing_2014 = df[df['Y2014'].isnull()]
print(f"{len(missing_2014)} were missing in 2014.")
missing_2014_percent = round((len(missing_2014)/len(df))*100,2)
print(f"{missing_2014_percent}% were missing in 2014")

1589 were missing in 2014.
2.61% were missing in 2014

In [13]:
# Question 8
sample = df.groupby('Item').sum()
print(sample)

                     Area Code  \
Item
Alcohol, Non-Food        38447
Alcoholic Beverages      75016
Animal Products          18060
Animal fats              85279
Apples and products      69280
...                        ...
Vegetables, Other        77779
Vegetal Products         18060
Wheat and products       87073
Wine                     66206
Yams                     50798

                                                                  Area  \
Item
Alcohol, Non-Food    AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAngo...
Alcoholic Beverages  AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Animal Products      AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaBeninBe...
Animal fats          AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Apples and products  AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
...                                                                ...
Vegetables, Other    AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Vegetal Products     AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaBeninBe...
Wheat and products   AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Wine                 AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Yams                 AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaAngolaB...

                     Item Code  Element Code  \
Item
Alcohol, Non-Food       752497       1515090
Alcoholic Beverages    1649136       2171381
Animal Products         397035         90990
Animal fats            1882494       2567303
Apples and products    1352989       1920418
...                        ...           ...
Vegetables, Other      1518715       2275409
Vegetal Products        391905         90990
Wheat and products     1639683       2654934
Wine                   1319535       1818328
Yams                    970905       1525745

                                                               Element  \
Item
Alcohol, Non-Food    ProductionImport QuantityStock VariationDomest...
Alcoholic Beverages  ProductionImport QuantityStock VariationExport...
Animal Products      Food supply (kcal/capita/day)Protein supply qu...
Animal fats          ProductionImport QuantityStock VariationExport...
Apples and products  ProductionImport QuantityStock VariationExport...
...                                                                ...
Vegetables, Other    ProductionImport QuantityStock VariationExport...
Vegetal Products     Food supply (kcal/capita/day)Protein supply qu...
Wheat and products   ProductionImport QuantityStock VariationExport...
Wine                 ProductionImport QuantityStock VariationExport...
Yams                 Export QuantityDomestic supply quantityResidua...

                                                                  Unit  \
Item
Alcohol, Non-Food    1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Alcoholic Beverages  1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Animal Products      kcal/capita/dayg/capita/dayg/capita/daykcal/ca...
Animal fats          1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Apples and products  1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
...                                                                ...
Vegetables, Other    1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Vegetal Products     kcal/capita/dayg/capita/dayg/capita/daykcal/ca...
Wheat and products   1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Wine                 1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Yams                 1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...

                         Y2014      Y2015      Y2016      Y2017      Y2018
Item
Alcohol, Non-Food      2403.00    2180.00    2223.00    2348.00    2293.00
Alcoholic Beverages  102410.11   98783.72   96958.75   95581.06   97847.27
Animal Products       11935.65   11811.73   11661.69   11547.65   11578.61
Animal fats          209460.54  200675.72  183314.22  269617.53  269648.27
Apples and products    9499.23   10559.15    9853.26   10198.90    9640.51
...                        ...        ...        ...        ...        ...
Vegetables, Other    155038.96  158104.08  156218.90  157752.59  163987.21
Vegetal Products     107145.19  107064.17  106792.72  107655.20  107775.39
Wheat and products   232670.13  234710.51  239377.07  240047.62  242645.19
Wine                   4497.36    4251.81    3872.09    4178.02    4039.32
Yams                 200396.96  203151.78  220626.20  229174.59  221272.09

[119 rows x 11 columns]

In [14]:
# Question 9
print(df.groupby('Element').sum())

                                        Area Code  \
Element
Domestic supply quantity                   708993
Export Quantity                            599910
Fat supply quantity (g/capita/day)         675050
Feed                                       176272
Food                                       663295
Food supply (kcal/capita/day)              674057
Food supply quantity (kg/capita/yr)        658446
Import Quantity                            688174
Losses                                     274353
Other uses (non-food)                      235554
Processing                                 271940
Production                                 526751
Protein supply quantity (g/capita/day)     675050
Residuals                                  623271
Seed                                       103537
Stock Variation                            571566
Total Population - Both sexes                6020
Tourist consumption                         50308

                                                                                     Area  \
Element
Domestic supply quantity                AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Export Quantity                         AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Fat supply quantity (g/capita/day)      AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Feed                                    AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Food                                    AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Food supply (kcal/capita/day)           AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Food supply quantity (kg/capita/yr)     AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Import Quantity                         AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Losses                                  AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Other uses (non-food)                   AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Processing                              AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Production                              AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Protein supply quantity (g/capita/day)  AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Residuals                               AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Seed                                    AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Stock Variation                         AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Total Population - Both sexes           AlgeriaAngolaBeninBotswanaBurkina FasoCabo Ver...
Tourist consumption                     AngolaAngolaBotswanaBotswanaBotswanaBotswanaBo...

                                        Item Code  \
Element
Domestic supply quantity                 14197445
Export Quantity                          11840553
Fat supply quantity (g/capita/day)       13535000
Feed                                      3538507
Food                                     13285035
Food supply (kcal/capita/day)            13511060
Food supply quantity (kg/capita/yr)      13185401
Import Quantity                          13795966
Losses                                    5424803
Other uses (non-food)                     4729749
Processing                                5350416
Production                               10450053
Protein supply quantity (g/capita/day)   13535000
Residuals                                12421089
Seed                                      2035933
Stock Variation                          11329527
Total Population - Both sexes              112545
Tourist consumption                       1486528

                                                                                     Item  \
Element
Domestic supply quantity                PopulationCereals - Excluding BeerWheat and pr...
Export Quantity                         Cereals - Excluding BeerWheat and productsRice...
Fat supply quantity (g/capita/day)      Grand TotalVegetal ProductsAnimal ProductsCere...
Feed                                    Cereals - Excluding BeerWheat and productsRice...
Food                                    Cereals - Excluding BeerWheat and productsRice...
Food supply (kcal/capita/day)           Grand TotalVegetal ProductsAnimal ProductsCere...
Food supply quantity (kg/capita/yr)     Cereals - Excluding BeerWheat and productsRice...
Import Quantity                         Cereals - Excluding BeerWheat and productsRice...
Losses                                  Cereals - Excluding BeerWheat and productsRice...
Other uses (non-food)                   Cereals - Excluding BeerWheat and productsStar...
Processing                              Cereals - Excluding BeerWheat and productsRice...
Production                              Cereals - Excluding BeerWheat and productsRice...
Protein supply quantity (g/capita/day)  Grand TotalVegetal ProductsAnimal ProductsCere...
Residuals                               Cereals - Excluding BeerWheat and productsRice...
Seed                                    Cereals - Excluding BeerWheat and productsRice...
Stock Variation                         Cereals - Excluding BeerWheat and productsRice...
Total Population - Both sexes           PopulationPopulationPopulationPopulationPopula...
Tourist consumption                     OilcropsGroundnuts (Shelled Eq)Cereals - Exclu...

                                        Element Code  \
Element
Domestic supply quantity                    28068795
Export Quantity                             26026133
Fat supply quantity (g/capita/day)           3435732
Feed                                         7282199
Food                                        25406622
Food supply (kcal/capita/day)                3329296
Food supply quantity (kg/capita/yr)          3163725
Import Quantity                             28834929
Losses                                      10292107
Other uses (non-food)                        8926728
Processing                                  10313310
Production                                  21388191
Protein supply quantity (g/capita/day)       3385502
Residuals                                   24066350
Seed                                         4211574
Stock Variation                             21464704
Total Population - Both sexes                  22995
Tourist consumption                          2869905

                                                                                     Unit  \
Element
Domestic supply quantity                1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Export Quantity                         1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Fat supply quantity (g/capita/day)      g/capita/dayg/capita/dayg/capita/dayg/capita/d...
Feed                                    1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Food                                    1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Food supply (kcal/capita/day)           kcal/capita/daykcal/capita/daykcal/capita/dayk...
Food supply quantity (kg/capita/yr)     kgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkg...
Import Quantity                         1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Losses                                  1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Other uses (non-food)                   1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Processing                              1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Production                              1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Protein supply quantity (g/capita/day)  g/capita/dayg/capita/dayg/capita/dayg/capita/d...
Residuals                               1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Seed                                    1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Stock Variation                         1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Total Population - Both sexes           1000 persons1000 persons1000 persons1000 perso...
Tourist consumption                     1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...

                                             Y2014       Y2015       Y2016  \
Element
Domestic supply quantity                1996716.35  2021493.55  2044842.70
Export Quantity                          150020.64   157614.47   151920.46
Fat supply quantity (g/capita/day)        10225.56    10235.74    10102.77
Feed                                     216927.89   225050.22   228958.65
Food                                    1212332.49  1232361.10  1247022.17
Food supply (kcal/capita/day)            454257.00   453383.00   451810.00
Food supply quantity (kg/capita/yr)       49650.63    49345.13    48985.28
Import Quantity                          274144.48   267018.46   286582.78
Losses                                   153223.00   155439.00   157787.00
Other uses (non-food)                     78718.13    66254.41    69563.68
Processing                               282923.00   287929.00   280631.00
Production                              1931287.75  1947019.39  1943537.15
Protein supply quantity (g/capita/day)    11836.46    11833.95    11779.69
Residuals                                 30149.00    30045.00    37224.00
Seed                                      21922.92    23976.82    23389.20
Stock Variation                           58749.83    34910.99    33140.12
Total Population - Both sexes           1031585.00  1058081.00  1085107.00
Tourist consumption                         416.00      349.00       89.00

                                             Y2017       Y2018
Element
Domestic supply quantity                2088198.10  2161192.10
Export Quantity                          182338.80   181594.80
Fat supply quantity (g/capita/day)        10253.84    10258.69
Feed                                     223705.68   233489.68
Food                                    1258888.28  1303841.28
Food supply (kcal/capita/day)            454681.00   455261.00
Food supply quantity (kg/capita/yr)       48690.04    49056.85
Import Quantity                          294559.09   287997.09
Losses                                   160614.00   163902.00
Other uses (non-food)                     91645.97    91300.97
Processing                               292836.00   308429.00
Production                              2030056.89  2075072.89
Protein supply quantity (g/capita/day)    11842.45    11833.56
Residuals                                 35500.00    34864.00
Seed                                      24870.14    25263.14
Stock Variation                           54316.91    20577.91
Total Population - Both sexes           1112641.00  1140605.00
Tourist consumption                          91.00       90.00

In [35]:
# Question 13
madagascar = df[(df['Area'] == 'Madagascar')]
# print(madagascar)
resultm = madagascar.groupby(['Element']).Y2015.sum()
print(resultm)

Element
Domestic supply quantity                  31214.98
Export Quantity                             494.75
Fat supply quantity (g/capita/day)           91.85
Feed                                       2070.22
Food                                      21120.65
Food supply (kcal/capita/day)              7685.00
Food supply quantity (kg/capita/yr)         871.59
Import Quantity                            1721.80
Losses                                     2176.00
Other uses (non-food)                      3957.12
Processing                                 1803.00
Production                                29482.89
Protein supply quantity (g/capita/day)      173.05
Residuals                                  -616.00
Seed                                        699.00
Stock Variation                            -505.00
Total Population - Both sexes             24234.00
Name: Y2015, dtype: float64

In [36]:
# Question 14
print(df['Area'].nunique())

49

In [41]:
# Question 19
area_sum = df.groupby('Area').Y2017.sum()
# print(area_sum)
area_sum.sort_values()

Area
Sudan (former)                       0.00
Ethiopia PDR                         0.00
Comoros                             59.84
Seychelles                         442.34
Sao Tome and Principe            12662.63
Cabo Verde                       14650.74
Guinea-Bissau                    19102.77
Lesotho                          21267.96
Botswana                         22101.30
Djibouti                         22729.91
Gambia                           23154.18
Gabon                            27979.64
Liberia                          29342.20
Namibia                          29874.89
Central African Republic         29937.00
Congo                            41181.68
Togo                             49841.88
Mauritius                        51114.83
Eswatini                         54343.33
Sierra Leone                     55311.33
Chad                             71594.68
Rwanda                           73663.69
Zimbabwe                         75919.34
Senegal                          95681.15
Guinea                           98138.87
Burkina Faso                    101855.07
Zambia                          103223.77
Tunisia                         124167.20
Benin                           124771.22
Niger                           126707.58
Madagascar                      131197.73
Mali                            149928.33
Mauritania                      156665.46
Mozambique                      161407.98
Malawi                          181098.71
Uganda                          213950.38
Côte d'Ivoire                   224599.01
Angola                          229159.57
Cameroon                        232030.43
Sudan                           239931.92
Kenya                           264660.66
United Republic of Tanzania     322616.85
Algeria                         325644.27
Ghana                           337599.06
Morocco                         388495.36
Ethiopia                        448683.76
South Africa                    517590.54
Egypt                           866379.92
Nigeria                        1483268.23
Name: Y2017, dtype: float64